### ISSUE TITLE
Uploaded photo does not appear in the results

### ISSUE THREAD

**Issue by esanmar** [aosasona/intellimage#1]
Hi,

I have uploaded the photo of my face with this prompt:
a portrait of me as a Real Madrid football player, hyper realistic, highly detailed
The result is a portrait of a football player but without my face.
How do I have to train the model to use my face?

Thanks!

**Comment by aosasona** [comment]
Hello @esanmar 
This wasn’t really a major project, it was simply to get a feel of the OpenAI API which means it is running on a free tier which in turn means it’s less accurate, and I currently setup this project to take either prompts or images but not both, but I could update that later, it’s just not quite a priority now, hope you understand :)

Feel free to fork this repo to play around with it :)
